### ISSUE TITLE
talk code location

### ISSUE THREAD

**Issue by patrickpierson** [python-frederick/talks#17]
@mblayman I just copied my code for the talk today to this repo. I noticed you put the tdd code in its own repo.  Is that prefered?

**Comment by mblayman** [comment]
I think that's probably fine. I put the TDD code in a separate repo because I included tags to act as checkpoints that people could look at individually. That would not have made sense for this repo.

Not everyone will have write access to this repo so I think we can take it on a case by case basis as to where code stuff should go.

Generally, if it's fairly small, then something like what you did is perfect. Keeping the code and presentation close together is a good thing.
